build automation consolidation

diff --git a/.github/workflows/static-analysis.yml b/.github/workflows/static-analysis.yml
--- a/.github/workflows/static-analysis.yml
+++ b/.github/workflows/static-analysis.yml
@@ -64,32 +64,35 @@ jobs:
         with:
           sarif_file: snyk.sarif
 
-  # lint:
-  #   name: Kubesec
-  #   needs: kustomize
-  #   runs-on: ubuntu-20.04
-  #   permissions:
-  #     actions: read
-  #     contents: read
-  #     security-events: write
+  kubescape:
+    name: Kubescape DevOps Best
+    needs: kustomize
+    runs-on: ubuntu-latest
+    steps:
+      - name: Install Kubescape
+        run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
 
-  #   steps:
+      - name: Download kustomize build YAML
+        uses: actions/download-artifact@v2
+        with:
+          name: kustomize
 
-  #     - name: Download kustomize build YAML
-  #       uses: actions/download-artifact@v2
-  #       with:
-  #         name: kustomize
+      - name: Run Kubescape
+        run: kubescape scan framework devopsbest --exclude-namespaces kube-system,kube-public kustomize.yaml # --enable-host-scan --fail-threshold 0
 
-  #     - name: Run kubesec scanner
-  #       uses: controlplaneio/kubesec-action@43d0ddff5ffee89a6bb9f29b64cd865411137b14
-  #       with:
-  #         input: kustomize.yaml # specify configuration file to scan here
-  #         format: template
-  #         template: template/sarif.tpl
-  #         output: kubesec-results.sarif
-  #         exit-code: "0"
+  datree:
+    name: Datree
+    needs: kustomize
+    runs-on: ubuntu-latest
 
-  #     - name: Upload Kubesec scan results to GitHub Security tab
-  #       uses: github/codeql-action/upload-sarif@v1
-  #       with:
-  #         sarif_file: kubesec-results.sarif
+    steps:
+      - name: Install Datree
+        run: curl https://get.datree.io | /bin/bash
+
+      - name: Download kustomize build YAML
+        uses: actions/download-artifact@v2
+        with:
+          name: kustomize
+
+      - name: Run Datree to check for Kubernetes misconfiguration issues
+        run: datree test --schema-version 1.21.0 --ignore-missing-schemas kustomize.yaml || exit 0
